### ISSUE TITLE
type="sysfs" resources not being written in special cases

### ISSUE THREAD

**Issue by Grapestain** [sonyxperiadev/thermanager#5]
Hi All,

Sorry if this is not the right forum, but here's something I'm figuring about thermanager. Let me know if there's a forum or other channel for such discussion, but it seems to be an issue after all anyway.

**Backstory:**
I have an old Z1 and trying to get few more months out of that old guy, but unfortunately I have a lot of issues with overheating. My research lead to thermanager as the best possible solution and I've made a very detailed thermanager.xml for my phone after I found out how basic was the config my ROM comes with out of the box (apparently originating from SONY, based on the file header).
It is working great... most the time... but.

The default settings of my kernel is to have Core Control and SoC temperature limit toggle enabled, which (at least one of them) as far as I've figured based on the behaviour of my phone responsible to turn of CPU cores if they are getting too hot. Which is nice, as it prevents the phone from burnout, however the bad thing is that once a CPU core is turned off this way, it won't turn back on until the next turn off/turn on cycle of the whole phone. This means that if my phone heats up, i must reboot it to become usable again as typically only cpu0 stays alive and it's way too slow.

So here comes thermanager and my custom configuration into the picture, which includes very detailed mitigation plan for the CPU core heating in order to prevent such situations.

**Issue:**
The issue I've been facing since I'm playing with the configuration that only cpu0 is getting mitigated (i.e. maximum frequency reduced by writing progressively smaller values into /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq as temp goes up), i've noticed however that cpu1, 2 and 3 is not being adjusted. I've tested with lot of different configurations, i've added detailed debug resources to my thermanager.xml so i could see in logcat which configurations and which mitigation levels are active (all seemed fine), eliminated union resources controlling each cpu core individually (no luck with that), and I've been looking at the scaling_max_freq files during stress test if they were being updated: they were not!

So long story short, here's **my theory of explanation:**
In my kernel CPU Hotplug (MDPrecision) is also enabled by default (and I think it's enabled in most kernels). Now when a core is offline the whole cpufreq directory is removed from under /sys/devices/system/cpu/cpu*, and it is back once the core is back online.
I've took a brief look at the source for thermanager and as far as I understood thermanager opens up the filesystem target of the sysfs resources at initialization and from than on it just assumes the file is open for writing. However if MDPrecision brings the core temporarily offline because the system load is low, the filesystem object is removed too which in turn I assume invalidates the write handle causing any subsequent mitigations to those cores fail. This however does not affect cpu0, as that one never goes offline.

My theory seem to be validated by the fact that if I disable MDPrecision and restart thermanager, the mitigations work as expected for all 4 CPU cores, no issues whatsoever.

The downside is that now all my CPU cores have to be online all the time which is not the best from battery life perspective, (also I have to do this manually after every boot as I didn't wanted to get into the making of a custom kernel with MDPrecision turned off).

**Possible solution**
Would it be possible to adjust the behaviour of thermanager to check sysfs resource file handles' validity before trying to write any values and acquiring a new handle if they are invalid for any reason? Or just see if the write was successful and try to reopen the file for writing if not and retry write?

Thank you!

**Comment by jerpelea** [comment]
Hi,
if you send me an email I will invite you to our slack 

For thermanager there are 2 options:

1.https://github.com/sonyxperiadev/kernel/commit/e7a0355b1967306f67cd309effa7236a7405a219
2.modify thermanager code to check sysfs and aquire a new handle 

Both should work

**Comment by Grapestain** [comment]
Hi,

I've sent you msg with my mail address on xda, thank you for your help!

I've also checked if i could use option 1. but apparently there's no /sys/module/msm_performance folder on my phone. Is that specific to some models only, or maybe it depends on the governor or kernel I'm using - if you may know?

**Comment by jerpelea** [comment]
Hi 
you can port it from our 3.10 kernel
